### PR TITLE
Sample data API

### PR DESCRIPTION
**Pull request by sabitertan**
This can help a new starter to understand better about API calls.

### CODE REVIEW

**Review by cereallarceny — DISMISSED** [review]
Nice work @sabitertan - but it looks like you copied the images to a new directory.  For sake of being clean, could you delete the old ones?  Please make sure that everything you moved, you also removed from its original location.

Likewise, we should commit the package-lock.json file to source control... please don't gitignore it.  Simply remove it from the files you've staged on this PR.  I like this PR, I'll merge it when you clean this up.

**Comment by sabitertan** [comment]
I don't have resolving rights for this PR, and IMO images shouldn't be a concern of app. They should be served by web server or varnish.

**Comment by cereallarceny** [comment]
I think you might be misunderstanding @sabitertan.  The PR you made has the same images in two locations, in the `src` folder **and** in the `public` folder.  You should probably delete the ones in `src`.  I believe you made a "copy", when you intended to "move" them.  :)

**Comment by sabitertan** [comment]
I think I am not following issue here I deleted ones under src/.  assets/ folder moved to public/, what else should be done?

**Comment by cereallarceny** [comment]
Ahh, my misunderstanding @sabitertan.  I am fine with the PR now but actually have 1 further improvement.  Let's move the API you built in the `data` directory into the existing `server` directory.  You can put your same logic in the `server/server.js` file and launch everything from the same `package.json` file.

Conceptually this PR is correct, but I would prefer to keep the folder structure smaller.  There's no need for a favicon and there's no need to add the `data` folder if we already have a node instance running in the `server` folder.

**Review by cereallarceny — CHANGES_REQUESTED** [review]
As per my last comment.  Move all of the server logic into the server folder, don't have a data folder.

**Pull request closed without merging**
